### ISSUE TITLE
GitHub API enricher is not working when running in OpenShift

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-catalog-apps#20]
Stacktrace:

```
2020-11-20 09:28:57,940 ERROR [io.sma.rea.mes.provider] (vert.x-eventloop-thread-0) SRMSG00200: The method io.quarkus.qe.Dispatcher#dispatchRepository has thrown an exception: javax.ws.rs.WebApplicationException: Unknown error, status code 403
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:16)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:39)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:154)
	at com.sun.proxy.$Proxy34.getRepositoryInfo(Unknown Source)
	at io.quarkus.qe.client.github.RepositoryClient_0e67fe48c1191e35d329694d3329ef73a68c897e_Synthetic_ClientProxy.getRepositoryInfo(RepositoryClient_0e67fe48c1191e35d329694d3329ef73a68c897e_Synthetic_ClientProxy.zig:159)
	at io.quarkus.qe.enricher.GitHubEnricher.enrichRepository(GitHubEnricher.java:31)
	at io.quarkus.qe.enricher.GitHubEnricher_ClientProxy.enrichRepository(GitHubEnricher_ClientProxy.zig:214)
	at io.quarkus.qe.Dispatcher.dispatchRepository(Dispatcher.java:29)
	at io.quarkus.qe.Dispatcher_ClientProxy.dispatchRepository(Dispatcher_ClientProxy.zig:185)
	at io.quarkus.qe.Dispatcher_SmallRyeMessagingInvoker_dispatchRepository_57057bd4d4852c655ddc67ab5d9825c7a38385cb.invoke(Dispatcher_SmallRyeMessagingInvoker_dispatchRepository_57057bd4d4852c655ddc67ab5d9825c7a38385cb.zig:48)
```

**Comment by michalvavrik** [comment]
Before we invest any effort into this, we would need to migrate Quarkus etc. Let's reopen if we run into this once the app is migrated and not with Quarkus 1.10.
